"""create_orders_table

Revision ID: 0001
Revises:
Create Date: 2026-01-01 00:00:01.000000

Bootstrap revision (HEAD of chain) for the Order Service order_db.

This revision performs two operations:

1. Enables the pgcrypto PostgreSQL extension to make gen_random_uuid()
   available as a server-side UUID v4 default. Required because all
   UUID primary keys in order_db (orders.id, eventually saga_state.saga_id
   in revision 0004) are server-generated when not supplied by the
   application.

2. Creates the orders aggregate-root table with the schema documented in
   AAP Section 0.4.4 and the folder spec for
   services/order-service/migrations/versions/.

orders is the aggregate root for the Order domain -- every other table
in order_db (order_items, order_status_history, saga_state) holds a
foreign key back to orders.id with ON DELETE CASCADE.

Schema highlights:
  * id: UUID PK, server-generated via gen_random_uuid().
  * user_id: OPAQUE UUID (no FK to user_db per AAP R-6).
  * status: TEXT with inline CHECK enforcing the 8-value enum
    matching domain.order.OrderStatus StrEnum.
  * currency: CHAR(3) ISO 4217 code (e.g., 'USD', 'INR').
  * total_amount: BIGINT in MINOR currency units, CHECK > 0.
  * idempotency_key: UNIQUE -- strongest possible duplicate-POST guard.
  * correlation_id: distributed tracing (AAP R-13).
  * version: INTEGER for optimistic locking by repository layer.

The pgcrypto extension is INTENTIONALLY NOT dropped in downgrade()
because (a) the extension may be in use by other concurrently-applied
revisions or shared schemas, and (b) dropping a PostgreSQL extension
that another object depends on errors out unconditionally. Operators
who truly want to remove pgcrypto must do so manually after dropping
all dependent objects.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration: enable pgcrypto then create orders table.

    Operation order:
      1. CREATE EXTENSION IF NOT EXISTS pgcrypto -- provides
         gen_random_uuid() for server-side UUID v4 generation.
      2. CREATE TABLE orders with all columns, CHECK constraints,
         UNIQUE on idempotency_key, and PRIMARY KEY on id.
      3. CREATE INDEX idx_orders__user_created on (user_id, created_at DESC)
         to support the dominant 'list orders for one user, newest first'
         query pattern.
    """
    # ------------------------------------------------------------------
    # Step 1: Enable pgcrypto.
    #
    # Subsequent column defaults reference gen_random_uuid(). If pgcrypto
    # is not enabled before the table is created, the CREATE TABLE will
    # succeed (defaults are evaluated at INSERT time, not DDL time), but
    # the first INSERT without an explicit `id` value will fail with
    # `function gen_random_uuid() does not exist`. Enabling first is
    # defensive and matches the sibling payment-service pattern.
    #
    # IF NOT EXISTS makes the operation idempotent: if a sibling service
    # shares the same database (not the case in production per AAP R-6,
    # but possible in shared dev compose environments), the extension
    # may already be enabled.
    # ------------------------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ------------------------------------------------------------------
    # Step 2: Create the orders aggregate-root table.
    #
    # 11 columns per the folder spec for services/order-service/
    # migrations/versions/. Constraints declared inline:
    #   - PRIMARY KEY on id (via primary_key=True).
    #   - UNIQUE on idempotency_key (named uq_orders__idempotency_key).
    #   - CHECK enforcing the 8-value status enum.
    #   - CHECK enforcing total_amount > 0.
    # ------------------------------------------------------------------
    op.create_table(
        "orders",
        # PRIMARY KEY: server-generated UUID v4. Application MAY supply
        # an explicit id (for testing or replay scenarios); when absent,
        # PostgreSQL generates one via gen_random_uuid() (provided by
        # pgcrypto, enabled above).
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
            comment="Order id (UUID v4, server-generated by default).",
        ),
        # OPAQUE user identifier (AAP R-6). NO foreign key to user_db's
        # users table. Validity is established at order creation by
        # JWT claim verification (the requesting user's sub claim is
        # the user_id).
        sa.Column(
            "user_id",
            sa.UUID(as_uuid=True),
            nullable=False,
            comment=(
                "Opaque user id (from JWT sub claim); NO cross-DB FK "
                "per AAP R-6."
            ),
        ),
        # Order status. Stored as TEXT, enforced by inline CHECK matching
        # the 8-value StrEnum in domain.order.OrderStatus.
        sa.Column(
            "status",
            sa.Text(),
            nullable=False,
            comment=(
                "Order status; one of CREATED, INVENTORY_RESERVED, "
                "PAYMENT_TAKEN, FULFILLED, COMPENSATING_INVENTORY, "
                "COMPENSATING_PAYMENT, CANCELLED, FAILED."
            ),
        ),
        # ISO 4217 currency code (e.g., 'USD', 'INR'). CHAR(3) so length
        # is constrained at the type level. The application layer enforces
        # the actual ISO 4217 set (the database does not maintain a
        # currency lookup table -- out of scope per AAP).
        sa.Column(
            "currency",
            sa.CHAR(3),
            nullable=False,
            comment="ISO 4217 currency code (e.g., 'USD', 'INR').",
        ),
        # Order total in MINOR currency units (e.g., cents for USD).
        # MUST be positive -- zero or negative orders are not valid.
        sa.Column(
            "total_amount",
            sa.BigInteger(),
            nullable=False,
            comment=(
                "Order total in MINOR currency units (e.g., cents). "
                "MUST be > 0."
            ),
        ),
        # Idempotency key for duplicate-POST suppression. UNIQUE so the
        # same key cannot create two orders. NULLABLE so legacy or
        # internally-triggered orders without a client-supplied key are
        # accepted (the application enforces presence on client routes).
        # PostgreSQL UNIQUE allows multiple NULLs (standard NULLs-distinct
        # semantics), so legacy/internal orders without a key coexist.
        sa.Column(
            "idempotency_key",
            sa.Text(),
            nullable=True,
            comment=(
                "Client-supplied idempotency key; UNIQUE when present. "
                "Strongest duplicate-POST guard per AAP and folder spec."
            ),
        ),
        # Distributed tracing correlation id (AAP R-13). Nullable for
        # background-generated orders without a request context.
        sa.Column(
            "correlation_id",
            sa.UUID(as_uuid=True),
            nullable=True,
            comment="Distributed-tracing correlation id (AAP R-13).",
        ),
        # Server-managed creation timestamp. Defaults to NOW() at INSERT.
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
            comment="Server-set creation timestamp.",
        ),
        # Server-managed update timestamp. Defaults to NOW() at INSERT.
        # Application MUST update this on every mutation (handled at the
        # ORM layer via the onupdate hook on the SQLAlchemy Column).
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
            comment="Updated on every mutation by the repository layer.",
        ),
        # Optimistic locking version. Application increments on every
        # successful update; SELECT-FOR-UPDATE clients verify version
        # match before committing. INTEGER (not BIGINT) is sufficient
        # because version increments per-row and a single order will
        # not see 2.1B updates in its lifetime.
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
            comment=(
                "Optimistic locking version; increments on every update."
            ),
        ),
        # ---- Constraints ----
        # PK is declared inline on id via primary_key=True; no explicit
        # PrimaryKeyConstraint is needed.
        #
        # UNIQUE on idempotency_key -- strongest duplicate-POST guard.
        # NULL values are NOT considered duplicate by PostgreSQL UNIQUE
        # semantics (multiple NULLs are allowed), so legacy/internal
        # orders without a key coexist.
        sa.UniqueConstraint(
            "idempotency_key",
            name="uq_orders__idempotency_key",
        ),
        # CHECK: status enum (8 UPPERCASE values, matches domain StrEnum
        # in services/order-service/src/orderservice/domain/order.py).
        # Any drift between database CHECK and application enum will
        # cause runtime errors on insert.
        sa.CheckConstraint(
            "status IN ("
            "'CREATED',"
            "'INVENTORY_RESERVED',"
            "'PAYMENT_TAKEN',"
            "'FULFILLED',"
            "'COMPENSATING_INVENTORY',"
            "'COMPENSATING_PAYMENT',"
            "'CANCELLED',"
            "'FAILED'"
            ")",
            name="ck_orders__status_enum",
        ),
        # CHECK: total_amount must be positive. Free orders (total = 0)
        # are not currently supported; if needed, a forward revision
        # would relax this CHECK.
        sa.CheckConstraint(
            "total_amount > 0",
            name="ck_orders__total_amount_positive",
        ),
        comment=(
            "Order aggregate root. Children: order_items, "
            "order_status_history, saga_state (all FK back via "
            "order_id with ON DELETE CASCADE)."
        ),
    )

    # ------------------------------------------------------------------
    # Step 3: Create composite index supporting the dominant query
    # pattern: 'list orders for user X, newest first'.
    #
    # DESC on created_at because customers always view newest orders
    # first; while B-tree serves both directions efficiently, ordering
    # matters for index-only scans on the common LIMIT 20 customer-
    # history query.
    #
    # Why raw SQL op.execute(...)?
    #   - The DESC qualifier on created_at requires either raw SQL
    #     `CREATE INDEX ... ON orders (user_id, created_at DESC)` OR
    #     SQLAlchemy expression syntax that is awkward and version-
    #     sensitive.
    #   - The raw SQL idiom is unambiguous, matches what `\d orders`
    #     shows when inspecting the index, and is consistent with the
    #     project's pattern of using op.execute(...) for any index that
    #     needs DESC ordering or a partial-index WHERE clause.
    # ------------------------------------------------------------------
    op.execute(
        "CREATE INDEX idx_orders__user_created "
        "ON orders (user_id, created_at DESC)"
    )


def downgrade() -> None:
    """Revert migration (local dev + CI round-trip only; never production).

    Drops the orders table and its index. The pgcrypto extension is
    INTENTIONALLY NOT dropped because (a) it may be required by other
    concurrently-active revisions, (b) PostgreSQL refuses to drop an
    extension that any database object depends on, making the drop
    fragile in shared dev environments. Operators who truly want
    pgcrypto removed must do so manually after all dependent objects
    are dropped.

    Use ONLY in local dev and CI round-trip tests; never invoke in
    production per the forward-only policy in ../README.md (AAP R-9).
    """
    # DROP INDEX IF EXISTS (raw SQL) is symmetric with the CREATE INDEX
    # raw SQL in upgrade(). IF EXISTS guards against double-downgrade.
    op.execute("DROP INDEX IF EXISTS idx_orders__user_created")
    # op.drop_table cascades to the PK, UNIQUE, and CHECK constraints.
    op.drop_table("orders")
    # Intentionally do NOT drop pgcrypto extension -- see docstring.
