"""create_warehouses

Revision ID: 0001
Revises:
Create Date: 2026-01-01 00:00:00.000000

Bootstrap revision (HEAD of the chain) for the Inventory Service's private
``inventory_db`` PostgreSQL database. This revision performs two responsibilities:

1. Enables the ``pgcrypto`` extension to make ``gen_random_uuid()`` available
   for UUID primary-key defaults across this service's schema. The extension is
   created idempotently with ``CREATE EXTENSION IF NOT EXISTS`` so re-applying
   this revision against a database that already has the extension is safe.
   Note: PostgreSQL 13+ ships ``gen_random_uuid()`` natively without pgcrypto,
   but enabling the extension explicitly preserves portability across managed
   PostgreSQL services that may run older versions.

2. Creates the ``warehouses`` registry table. This table is the FK target for
   ``stock_items`` (revision 0002), ``reservation_items`` (revision 0003), and
   ``stock_movements`` (revision 0004), so it MUST be created before any of
   those tables. The numeric filename prefix (0001) and the empty
   ``down_revision`` formalize this ordering invariant.

Schema (per AAP Section 0.4.4 + parent folder README.md):
    * id           UUID PK   DEFAULT gen_random_uuid()
    * name         VARCHAR(128) NOT NULL UNIQUE
    * region       VARCHAR(32)  NOT NULL
    * status       VARCHAR(16)  NOT NULL CHECK status IN
                       ('ACTIVE', 'MAINTENANCE', 'DECOMMISSIONED')
    * adapter_type VARCHAR(32)  NOT NULL DEFAULT 'database'
                       CHECK adapter_type IN ('database', 'external_wms')
    * config       JSONB        NOT NULL DEFAULT '{}'::jsonb
    * created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
    * updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()

Architectural notes:
    * The ``status`` enum is UPPERCASE and must agree byte-for-byte with the
      ``WarehouseStatus`` StrEnum defined in ``../../src/domain/`` (cross-coupling
      enforced by the runtime CHECK constraint).
    * The ``adapter_type`` enum is lowercase and drives the runtime adapter
      strategy pattern (AAP Section 0.4.3): ``DatabaseWarehouseAdapter`` (default)
      vs. ``ExternalWMSWarehouseAdapter`` (future). Hard-coded adapter selection
      is forbidden; the column is the single source of truth.
    * The ``config`` JSONB column carries adapter-specific configuration (e.g.,
      WMS endpoint URL, sync interval). Empty default ``'{}'::jsonb`` is safe.
    * ``pgcrypto`` is INTENTIONALLY NOT dropped in ``downgrade()``: the extension
      may be shared with sibling services in dev environments, and ``DROP
      EXTENSION`` would fail if any object depends on it. This is consistent
      with the order-service / payment-service / notification-service convention.

References:
    * AAP Section 0.4.4 -- inventory_db schema
    * AAP R-6 -- Database per service strict isolation
    * AAP R-7 -- PostgreSQL for ACID transactional integrity
    * AAP R-9 -- Migrations under owning service
    * Parent folder README.md -- Schema specification verbatim
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration: enable pgcrypto and create the warehouses table."""
    # Enable pgcrypto for gen_random_uuid() -- idempotent.
    # Note: PostgreSQL 13+ ships gen_random_uuid() natively, but enabling the
    # extension explicitly preserves portability across managed Postgres versions.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    op.create_table(
        "warehouses",
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
            comment="Surrogate UUID primary key (v4) generated by pgcrypto.",
        ),
        sa.Column(
            "name",
            sa.String(length=128),
            nullable=False,
            comment="Human-readable warehouse name (must be globally unique within this service).",
        ),
        sa.Column(
            "region",
            sa.String(length=32),
            nullable=False,
            comment="Geographic region identifier (e.g., 'us-east-1', 'eu-west-1', 'ap-south-1').",
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            comment=(
                "Operational status. UPPERCASE enum coupled with the "
                "WarehouseStatus StrEnum in ../../src/domain/. Values: "
                "ACTIVE | MAINTENANCE | DECOMMISSIONED."
            ),
        ),
        sa.Column(
            "adapter_type",
            sa.String(length=32),
            nullable=False,
            server_default=sa.text("'database'"),
            comment=(
                "Drives runtime adapter strategy selection per AAP Section 0.4.3. "
                "Lowercase enum: 'database' (default DatabaseWarehouseAdapter) | "
                "'external_wms' (future ExternalWMSWarehouseAdapter)."
            ),
        ),
        sa.Column(
            "config",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
            comment=(
                "Adapter-specific configuration (e.g., WMS endpoint URL, sync interval). "
                "Empty default '{}'::jsonb is safe; adapter implementations validate the "
                "shape they require."
            ),
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
            comment="Row creation timestamp (UTC).",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
            comment="Last row mutation timestamp (UTC). Application is responsible for updating.",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_warehouses"),
        sa.UniqueConstraint("name", name="uq_warehouses__name"),
        sa.CheckConstraint(
            "status IN ('ACTIVE', 'MAINTENANCE', 'DECOMMISSIONED')",
            name="ck_warehouses__status_enum",
        ),
        sa.CheckConstraint(
            "adapter_type IN ('database', 'external_wms')",
            name="ck_warehouses__adapter_type_enum",
        ),
        comment=(
            "Warehouse registry. FK target for stock_items.warehouse_id, "
            "reservation_items.warehouse_id, and stock_movements.warehouse_id. "
            "Per AAP R-6, this table is private to the Inventory Service."
        ),
    )


def downgrade() -> None:
    """Revert migration (local dev + CI round-trip only; never production).

    Drops the warehouses table. The pgcrypto extension is intentionally NOT
    dropped because it may be shared with sibling services in dev environments,
    and DROP EXTENSION would fail if any other object in the database depends
    on it.
    """
    op.drop_table("warehouses")
