"""create_stock_items

Revision ID: 0002
Revises: 0001
Create Date: 2026-01-01 00:00:01.000000

Creates the ``stock_items`` table -- the per-(product_id, warehouse_id)
inventory-state row that is the centerpiece of the reservation engine.

This table is the **hot path** of the entire service: every ``order.created``
event triggers an UPDATE here within a single transaction, and every stock
lookup endpoint reads from here. Concurrency correctness is enforced through:

  * **Optimistic locking** via the ``version`` BIGINT column. The repository
    layer issues UPDATEs with ``WHERE id = :id AND version = :expected_version``
    and SETs ``version = :expected_version + 1``. A row count of 0 from the
    UPDATE indicates a concurrent transaction won the race; the application
    retries per the AAP R-15 backoff policy (STOCK_OPTIMISTIC_LOCK_*).
  * **CHECK constraints** ``available_qty >= 0`` and ``reserved_qty >= 0`` as
    defense-in-depth: the application logic should never produce negative
    quantities, but a malformed admin replenishment SQL would fail loudly here
    rather than silently corrupt state.
  * **Composite UNIQUE constraint** ``(product_id, warehouse_id)``: exactly
    one row per (SKU, warehouse) tuple. The repository layer relies on this
    invariant for the ``ON CONFLICT (product_id, warehouse_id)`` upsert path
    used by stock replenishment workflows.

Cross-service-FK discipline (AAP R-6):
  * ``product_id`` is an OPAQUE UUID -- there is **no FK** pointing at the
    Product Service's ``products`` collection. Product Service owns
    ``product_db`` (MongoDB) and Inventory Service receives ``product.created``
    / ``product.updated`` events to maintain its local stock_items rows.
    Cross-service joins are forbidden.
  * ``warehouse_id`` IS an intra-service FK (REFERENCES warehouses(id)) because
    ``warehouses`` lives in the SAME ``inventory_db``. NO CASCADE -- warehouse
    decommissioning is an explicit operational task that must move stock
    rather than silently delete it.

Schema (per AAP Section 0.4.4 + parent folder README.md):
    * id                    UUID PK   DEFAULT gen_random_uuid()
    * product_id            UUID      NOT NULL  (opaque; no FK -- AAP R-6)
    * warehouse_id          UUID      NOT NULL  (FK -> warehouses.id, NO CASCADE)
    * available_qty         INTEGER   NOT NULL  CHECK (available_qty >= 0)
    * reserved_qty          INTEGER   NOT NULL  DEFAULT 0
                                                CHECK (reserved_qty >= 0)
    * low_stock_threshold   INTEGER   NOT NULL  DEFAULT 10
                                                CHECK (low_stock_threshold >= 0)
    * version               BIGINT    NOT NULL  DEFAULT 0   (optimistic lock -- R-15)
    * created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
    * updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
    * UNIQUE (product_id, warehouse_id)

References:
    * AAP Section 0.4.4 -- inventory_db schema
    * AAP R-6  -- Database per service strict isolation (no cross-service FKs)
    * AAP R-7  -- PostgreSQL for ACID transactional integrity
    * AAP R-15 -- Optimistic-lock retry policy on contended SKUs
    * Parent folder README.md -- Schema specification verbatim
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration: create the stock_items table.

    Depends on revision 0001 (warehouses table + pgcrypto extension).
    """
    op.create_table(
        "stock_items",
        sa.Column(
            "id",
            sa.UUID(as_uuid=True),
            primary_key=True,
            nullable=False,
            server_default=sa.text("gen_random_uuid()"),
            comment="Surrogate UUID primary key (v4) generated by pgcrypto.",
        ),
        sa.Column(
            "product_id",
            sa.UUID(as_uuid=True),
            nullable=False,
            comment=(
                "Opaque product identifier owned by the Product Service "
                "(product_db, MongoDB). NO FK constraint per AAP R-6 -- "
                "cross-service joins are forbidden; consistency is "
                "maintained via Kafka product.* events."
            ),
        ),
        sa.Column(
            "warehouse_id",
            sa.UUID(as_uuid=True),
            nullable=False,
            comment=(
                "Intra-service FK to warehouses.id. NO CASCADE -- warehouse "
                "decommissioning is an explicit operational task that must "
                "drain stock to other warehouses before deletion is permitted."
            ),
        ),
        sa.Column(
            "available_qty",
            sa.Integer(),
            nullable=False,
            comment=(
                "Units available for reservation. Decremented on order.created "
                "(after FOR UPDATE + version check); incremented on "
                "order.cancelled, expired reservation, or stock replenishment."
            ),
        ),
        sa.Column(
            "reserved_qty",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
            comment=(
                "Units currently held by ACTIVE reservations. Incremented on "
                "order.created; decremented on order.cancelled, "
                "order.fulfilled, or expired reservation."
            ),
        ),
        sa.Column(
            "low_stock_threshold",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("10"),
            comment=(
                "Per-SKU low-stock alarm threshold. When available_qty drops "
                "below this value, an inventory.low-stock Kafka event is "
                "emitted (consumed by Notification Service for ops alerts and "
                "by Recommendation Engine to suppress recommendations). "
                "Default 10; configurable per row via admin endpoint."
            ),
        ),
        sa.Column(
            "version",
            sa.BigInteger(),
            nullable=False,
            server_default=sa.text("0"),
            comment=(
                "Optimistic locking column (AAP R-15). Repository UPDATEs "
                "include WHERE version = :expected and SET version = :expected + 1. "
                "BIGINT accommodates many years of high-volume increments before "
                "wraparound (~9.2e18 increments)."
            ),
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
            comment="Row creation timestamp (UTC).",
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
            comment="Last row mutation timestamp (UTC). Updated by repository on every UPDATE.",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_stock_items"),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name="fk_stock_items__warehouse_id__warehouses",
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "product_id",
            "warehouse_id",
            name="uq_stock_items__product_warehouse",
        ),
        sa.CheckConstraint(
            "available_qty >= 0",
            name="ck_stock_items__available_qty_non_negative",
        ),
        sa.CheckConstraint(
            "reserved_qty >= 0",
            name="ck_stock_items__reserved_qty_non_negative",
        ),
        sa.CheckConstraint(
            "low_stock_threshold >= 0",
            name="ck_stock_items__low_stock_threshold_non_negative",
        ),
        comment=(
            "Per-(product_id, warehouse_id) inventory-state row. "
            "The hot path of the reservation engine. Optimistic locking via "
            "the version column (AAP R-15). UNIQUE (product_id, warehouse_id) "
            "enforces one row per SKU per warehouse."
        ),
    )


def downgrade() -> None:
    """Revert migration (local dev + CI round-trip only; never production).

    Drops the stock_items table. Implicitly drops the FK to warehouses, the
    UNIQUE constraint, and all CHECK constraints. The warehouses table
    (revision 0001) remains intact.
    """
    op.drop_table("stock_items")
