"""seed_default_warehouse

Revision ID: 0005
Revises: 0004
Create Date: 2026-01-01 00:00:04.000000

Inserts a single default warehouse row into the ``warehouses`` table for
local-development convenience.

This is a **data migration**, not a DDL migration. It contains no
``op.create_table`` / ``op.alter_column`` / ``op.drop_*`` calls. The only
operation is an idempotent INSERT.

Idempotency guarantee:
    The INSERT uses ``ON CONFLICT (name) DO NOTHING`` against the
    ``uq_warehouses__name`` unique constraint (created in revision 0001).
    Re-running this revision after a partial failure or a dev-environment
    rebuild is safe -- duplicate inserts are silently absorbed.

Production opt-out:
    Per parent folder README.md, production environments may opt out of
    seed-data revisions by setting the environment variable
    ``INVENTORY_SKIP_SEED=true``. When set, the ``upgrade()`` function
    short-circuits before any INSERT is issued and logs a notice. This
    avoids polluting production data with development-only seed rows
    while keeping the migration chain unbroken (revision 0006 still
    applies cleanly on production).

Default warehouse properties:
    * id            -- auto-generated by the ``gen_random_uuid()`` DEFAULT
                       on warehouses.id (set in revision 0001)
    * name          = 'default'
    * region        = 'us-east-1'
    * status        = 'ACTIVE'
    * adapter_type  -- defaults to 'database' (warehouses.adapter_type DEFAULT)
    * config        -- defaults to '{}'::jsonb
    * created_at    -- defaults to NOW()
    * updated_at    -- defaults to NOW()

The 'default' warehouse is the placeholder warehouse that local-dev
``stock_items`` rows reference. Production deployments seed real warehouses
through the Warehouse admin endpoint (a future feature) or via Kafka
``warehouse.created`` events from a dedicated provisioning workflow.

References:
    * Parent folder README.md -- Default warehouse seed mandate + opt-out flag
    * Revision 0001 -- uq_warehouses__name UNIQUE constraint enabling
      ON CONFLICT (name) DO NOTHING
"""

import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: Union[str, Sequence[str], None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ---------------------------------------------------------------------------
# Production opt-out flag.
#
# Set INVENTORY_SKIP_SEED=true (or any truthy variant: '1', 'yes', 'on') to
# skip seeding in production / staging environments. The migration chain
# remains intact (revision 0006 still applies); only the INSERT is bypassed.
# ---------------------------------------------------------------------------
_SKIP_SEED_ENV_VAR = "INVENTORY_SKIP_SEED"
_TRUTHY_VALUES = frozenset({"1", "true", "yes", "on", "y", "t"})


def _is_seed_skipped() -> bool:
    """Return True if the seed should be skipped per the opt-out env var.

    Reads the ``INVENTORY_SKIP_SEED`` environment variable and matches its
    value (case-insensitive, after stripping leading/trailing whitespace)
    against a documented whitelist of truthy spellings. Anything else --
    including an unset variable, an empty string, "false", "no", "0",
    "disabled", or a typo -- is interpreted as "do seed" (the safe
    default for development).

    The whitelist approach is intentional: it avoids surprising operators
    who might set ``INVENTORY_SKIP_SEED=`` (empty), ``=false``, or
    ``=disabled`` and expect different semantics. The seed path is
    idempotent and safe to re-run, so the failure mode of "seed when
    skip was intended" is benign in development; the failure mode of
    "skip when seed was intended" would silently leave dev databases
    without the default warehouse and surprise developers downstream.
    """
    raw = os.environ.get(_SKIP_SEED_ENV_VAR, "").strip().lower()
    return raw in _TRUTHY_VALUES


def upgrade() -> None:
    """Apply forward migration: insert the default warehouse row.

    The INSERT is idempotent -- re-running this revision (after partial
    failure, container restart, or dev-database rebuild) is safe because
    of the ``ON CONFLICT (name) DO NOTHING`` clause against the
    ``uq_warehouses__name`` unique constraint.

    If the environment variable ``INVENTORY_SKIP_SEED`` is set to a truthy
    value, the seed is bypassed entirely. The revision still applies and
    stamps the alembic_version_inventory_service table; only the INSERT
    is skipped.
    """
    if _is_seed_skipped():
        # Production opt-out path. The bind connection is not used; we
        # just emit a notice via raw SQL so it appears in the migration
        # log without requiring a Python logger.
        op.execute(
            "DO $$ BEGIN RAISE NOTICE "
            "'INVENTORY_SKIP_SEED is set; skipping default warehouse seed.'; "
            "END $$;"
        )
        return

    # Idempotent INSERT of the local-dev default warehouse.
    #
    # Only the three NOT NULL columns without DEFAULTs are listed:
    #   - name   (UNIQUE, used as the ON CONFLICT target)
    #   - region (NOT NULL)
    #   - status (NOT NULL, CHECK constraint enforces 'ACTIVE'/'INACTIVE'/...)
    #
    # Every other column relies on its column DEFAULT from revision 0001:
    #   - id           = gen_random_uuid()
    #   - adapter_type = 'database'
    #   - config       = '{}'::jsonb
    #   - created_at   = NOW()
    #   - updated_at   = NOW()
    #
    # ON CONFLICT (name) DO NOTHING references the uq_warehouses__name
    # UNIQUE constraint by column tuple; this is more portable than
    # naming the constraint and matches PostgreSQL's recommended idiom
    # for idempotent upserts where the conflict target is a single column.
    op.execute(
        sa.text(
            "INSERT INTO warehouses (name, region, status) "
            "VALUES ('default', 'us-east-1', 'ACTIVE') "
            "ON CONFLICT (name) DO NOTHING"
        )
    )


def downgrade() -> None:
    """Revert migration (local dev + CI round-trip only; never production).

    Removes the default warehouse row IF AND ONLY IF no stock_items rows
    reference it. If the warehouse has dependent stock_items, the DELETE
    is silently no-op'd (the warehouse_id FK from stock_items has
    ON DELETE RESTRICT, so a naive DELETE would fail with a constraint
    violation that aborts the entire downgrade transaction).

    To accommodate the CASCADE-restrictive design, this downgrade uses a
    NOT EXISTS guard: only deletes the default warehouse if no stock_items
    or reservation_items reference it. In a clean CI round-trip
    (upgrade head -> downgrade base -> upgrade head), there are no
    stock_items, so the DELETE removes the row cleanly. In a real dev
    database where a developer has populated stock_items, the DELETE is
    a no-op and the developer must manually clean up before retrying
    downgrade.
    """
    if _is_seed_skipped():
        # Symmetric: if upgrade was skipped, downgrade is also a no-op.
        return

    # Defensive DELETE: only removes the 'default' warehouse if no child
    # rows reference it via FK (stock_items.warehouse_id,
    # reservation_items.warehouse_id, stock_movements.warehouse_id).
    # All three FKs have ON DELETE RESTRICT, so an unguarded DELETE would
    # raise a constraint violation in any dev database with seeded child
    # data and abort the entire downgrade transaction. The NOT EXISTS
    # guards make this DELETE survivable across both clean CI round-trips
    # (where child tables are empty) and developer-populated databases
    # (where the DELETE is a silent no-op).
    op.execute(
        sa.text(
            "DELETE FROM warehouses "
            "WHERE name = 'default' "
            "AND NOT EXISTS ("
            "    SELECT 1 FROM stock_items WHERE warehouse_id = warehouses.id"
            ") "
            "AND NOT EXISTS ("
            "    SELECT 1 FROM reservation_items WHERE warehouse_id = warehouses.id"
            ") "
            "AND NOT EXISTS ("
            "    SELECT 1 FROM stock_movements WHERE warehouse_id = warehouses.id"
            ")"
        )
    )
